-d /media/sf_riscv-ss/src/riscv-ss/impl/gwsynthesis/riscv-ss.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /media/sf_riscv-ss/src/riscv-ss.cst
-cfg /media/sf_riscv-ss/src/riscv-ss/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
